[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test/solidity"
cache_path = "cache_forge"
optimizer = true
optimizer_runs = 200

# Allow file system access for deployment scripts
fs_permissions = [
    { access = "write", path = "./deployment.json" }
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
